package com.example.demo.mybatis.domain;

public class BlogKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.id
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	private Integer id;
	
	public BlogKey() {
	}

	public BlogKey(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.id
	 * @return  the value of blog.id
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.id
	 * @param id  the value for blog.id
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}
}