package com.thinkerwolf.frameworkstudy.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.thinkerwolf.frameworkstudy.mybatis.domain.Blog;
import com.thinkerwolf.frameworkstudy.mybatis.domain.BlogExample;
import com.thinkerwolf.frameworkstudy.mybatis.domain.BlogKey;

public interface BlogMapper {
	
	@Select("select * from blog where id = #{id}")
	Blog selectOneBlog(int id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	long countByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int deleteByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int deleteByPrimaryKey(BlogKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int insert(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int insertSelective(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	List<Blog> selectByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	Blog selectByPrimaryKey(BlogKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int updateByPrimaryKeySelective(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Tue Oct 16 15:53:40 CST 2018
	 */
	int updateByPrimaryKey(Blog record);
}